// create budget item table

CREATE TABLE BudgetItem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    itemName VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    amount INTEGER NOT NULL,
    date DATE NOT NULL,
    category VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL
);